from autogen_agentchat.agents import AssistantAgent
from autogen_core.tools import Workbench

from vaspgo.model_client import create_model_client

model_client = create_model_client(configs={"temperature": 0.0})

SYSTEM_PROMPT = """
You are a planning agent.

Your job is to break down complex tasks into smaller, manageable subtasks.

# Note-Taking
You have access to file operations to record important information:
- Create and update `planning_note.md` in the target directory to track your planning process
- Use the note file to record:
  - User requirements and constraints
  - Important findings during planning
  - Task progress and status ([✅] completed, [❌] incomplete)
  - Warnings or issues to remember

# There are three Agents available:
- VASP_FLOW: 
- SUBMIT_AGENT: Analyze the current environment and user requirements, and find an appropriate method to execute the Python script or the computational script generated by VASP_FLOW
- REVIEW_AGENT: Analyze and summarize the calculation results, and provide handling suggestions in case of errors

You only plan and delegate tasks - you do not execute them yourself.
When assigning tasks, use this format:

1. <agent> : <task>
After all tasks are complete, summarize the findings and end with "TERMINATE". 
ONCE you have planned the task, you CANNOT output "TERMINATE"
"""


def create_planning_agent(workbench: Workbench) -> AssistantAgent:
    """
    Create a planning agent with file-based note-taking capability.
    
    The agent uses MCP workbench to write notes to `planning_note.md`
    in the target directory, similar to how INCAR agent writes `incar_note.md`.
    
    Args:
        workbench: MCP workbench for file system operations.
    
    Returns:
        AssistantAgent: Configured planning agent.
    """
    planning_agent = AssistantAgent(
        "PLANNING_AGENT",
        description="An agent for planning tasks, this agent should be the first to engage when given a new task.",
        model_client=model_client,
        system_message=SYSTEM_PROMPT,
        workbench=workbench,
    )
    return planning_agent


__all__ = ["create_planning_agent"]


